### ISSUE TITLE
My suggestions and issues report

### ISSUE THREAD

**Issue by Drac1652** [Noname968/airin#30]
I really like the way you put the website is Okay and perculiar, what i like the most is fast reload and ad free. But there're quite a few things that make it not perfect..
Issues.
1. I can't open my profile or my list data from anilist 
2. Sometimes when i search anime by their names it only shows "no results found" even though the anime is present in homepage.
Suggestions.
1. Addition of next and prev buttons on preview on home page.
2. Making the whole homepage in grid (For top anime and most popular)
3. And also you may visit (shiroko.co) just to get some details on how they put their interface and also their player.

I wish you the best and your work is a masterpiece

**Comment by Noname968** [comment]
Profile viewing is fixed in the next update.
And sure i will include some suggestions in the website.
