### ISSUE TITLE
Site Deployment Failed + not working properly.

### ISSUE THREAD

**Issue by skgupta507** [Noname968/airin#32]
hey @Noname968 the site failed to load after deployment the error i got was **500|internal server error** .i have attached the screenshot of the same. Kindly guide me through the process to fix this issue.
![image](https://github.com/Noname968/airin/assets/131786207/c8c88c61-4d04-4f70-ba54-7738b00aab93)

one more thing after refreshing it 4-5 times it works but then when u click on watch now button i get a error called **A client-side eception has accured** i have attached screenshot of that also.
![image](https://github.com/Noname968/airin/assets/131786207/ab04cf4b-8851-44e4-8107-8f8e70fc636c)

**Comment by Noname968** [comment]
maybe u did not configure the env properly

**Comment by Noname968** [comment]
if u did configure the env correctly and still get the error then dm in discord

**Comment by skgupta507** [comment]
hello @Noname968 i have messaged ur id luckyhv on discord pls respond as soon as possible.

**Comment by heyjumanji** [comment]
@skgupta507 Did your error fix?

**Comment by skgupta507** [comment]
> @skgupta507 Did your error fix?

NOT YET @heyjumanji  iam still facing the same issue till now

**Comment by Noname968** [comment]
I deployed again it works fine for me

**Comment by Noname968** [comment]
Send me your .env file I will check with your details.

**Comment by skgupta507** [comment]
NEXT_PUBLIC_PROXY_URI
https://animedexproxy.sunilk98850.workers.dev

CONSUMET_URI
https://api-consumet-org-olive.vercel.app

MALSYNC_URI
https://api.malsync.moe/mal/anime/anilist:

MONGODB_URI
mongodb+srv://sunilk98850:oO8ppRnR8LgiTuhh@cluster0.kq5monm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

NEXT_PUBLIC_DEV_URL
http://localhost:3000

NEXT_PUBLIC_PRODUCTION_URL
https://airinx.vercel.app

REDIS_URL
rediss://default:AVNS_ulIEIaZTqaQpT1hVgMC@redis-1afb2aeb-sunilk98850-484f.a.aivencloud.com:12053

GRAPHQL_ENDPOINT
https://graphql.anilist.co

ZORO_URI
https://aniwatch-apii.vercel.app

ANILIST_CLIENT_ID
18519

ANILIST_CLIENT_SECRET
uVIjxEY3KO4HfVTOUOxuamzAwkSSrd5CX83dLe7R

NEXTAUTH_SECRET
Kbw0nwwPcAQOZXDG96H0bZfnI5j8kvYjdfAzjucHMTM

NEXTAUTH_URL
https://airinx.vercel.app


> Send me your .env file I will check with your details.

this is my .env @Noname968

**Comment by Noname968** [comment]
I think its fixed. Once update the new env it should work. I will also remove mandatory mongodb uri and push the changes.
